### ISSUE TITLE
working except....

### ISSUE THREAD

**Issue by Paolo2016** [orvtech/efi-bruteforce#11]
After a bunch of fooling around I have gotten it all working except 1 thing I noticed. It has been running lal night and now I am at the 4 box PIN lock screen, it takes a couple of tries and then says that I will have to try again in like 4-5minutes...... but I believe that the Teensy is still calculating..... Is there anyway to account for this? I am not a programmer so it is very difficult for me...

**Comment by orvtech** [comment]
So there are 2 separate sketches. One for the iCloud (4 box PIN lock screen) and one for the EFI lock (a single input box field that allows many characters).

The iCloud script accounts for this down time. If you were at the single box screen and now are at the 4box screen that means that at some point it the PIN was found.

I see no issue to fix this, the code is working as expected.

**Comment by Paolo2016** [comment]
ok, I see what you mean that the code was found. that's great!. but how would I know what the code was? I mean should it not have unlocked and shown the system? or would I have to go through both of the screens?

**Comment by orvtech** [comment]
@Paolo2016 there is a shell script that tracks that, you need to run it in parallel and it will tell you the range of where that number is. You can then try each number in that range by hand or modify the sketch to go over that range only and repeat the process.

Here is the script: https://github.com/orvtech/efi-bruteforce/blob/master/efi_range_tracker.sh
