### ISSUE TITLE
Confirm it still works on teensy 2.0

### ISSUE THREAD

**Issue by ashyoff** [orvtech/efi-bruteforce#7]
Got teensy 2.0 for $15 and finally it gets the right pin (4 digits), however I had to comment keyboard_modifier_keys = 0; to make it compilable else it gave me errors.

**Comment by superdave16** [comment]
i changed keyboard_modifier_keys = 0;
to
Keyboard.set_modifier(0);
testing on teensy++2.0

**Comment by abyromani** [comment]
Yrses i still working on it
Sent from my 4G LTE Device-------- Original message --------From: superdave16 <notifications@github.com> Date: 1/11/2016  4:05 AM  (GMT-04:00) To: orvtech/efi-bruteforce <efi-bruteforce@noreply.github.com> Subject: Re: [efi-bruteforce] Confirm it still works on teensy 2.0 (#7) 
i changed keyboard_modifier_keys = 0;

to

Keyboard.set_modifier(0);

testing on teensy++2.0

**Comment by maelpalala** [comment]
Teensy 2.0++ this card works ?
