### ISSUE TITLE
Get this error on the tracker script

### ISSUE THREAD

**Issue by superdave16** [orvtech/efi-bruteforce#8]
syntax error near unexpected token `done'
./tracker.sh: line 11:`done'

running latest kali. any ideas?

**Comment by superdave16** [comment]
this error could be the fact that im not using fedora. as u tested in fedora im using kali.

**Comment by orvtech** [comment]
You probably copied the code instead of downloading it and had a typo while doing so. This has nothing to do with Kali or Fedora
